services:

  core-service:
    build:
      context: .
      dockerfile: ./core-service.Dockerfile
    restart: unless-stopped
    expose:
      - "80"
  

  user-service:
    build:
      context: .
      dockerfile: ./user-service.Dockerfile
    restart: unless-stopped
    expose:
      - "80"

  loadbalancer:
    image: nginx:stable-alpine3.20
    ports:
      - 8080:80
    volumes:
      - ./templates:/etc/nginx/templates
      - ./frontend:/var/www/frontend
    depends_on:
      - core-service
      - user-service
    
