services:

  core-service:
    build:
      context: .
      dockerfile: ./core-service.Dockerfile
    restart: unless-stopped
    expose:
      - "80"
  

  user-service:
    build:
      context: .
      dockerfile: ./user-service.Dockerfile
    restart: unless-stopped
    expose:
      - "80"

  loadbalancer:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./frontend:/usr/share/nginx/html/frontend
    depends_on:
      - core-service
      - user-service
